### ISSUE TITLE
Ajouter les liens IMDB pour tous les films

### ISSUE THREAD

**Issue by MarinePereira** [m2dimi/ciwo#1]
Pour les 1000 films, il faut ajouter les liens IMDB des films.

**Comment by tonydimi** [comment]
On divise le travail en 3 entre Sophie, Marine et moi. Je commence par le fichier Comédie

**Comment by MarinePereira** [comment]
Je fais le fichier "Drame".

**Comment by tonydimi** [comment]
J'ai fini le fichier Comédie. Je commence les 135 premiers de Action-aventure

**Comment by MarinePereira** [comment]
J'ai terminé la partie "Drame" et fait les 3/4 du genre "Thriller". 
Tony et Sophie dès que vous avez terminé, vous me le dites svp ? Comme ça on envoie le mail au prof.
Au faite, pour les films qui n'apparaissent pas dans IMDB j'ai mis la page Wikipédia quand c'était possible, sinon rien.

**Comment by tonydimi** [comment]
J'ai également fini la partie "Comédie" et fais les 135 premiers de "Action-Aventure".

**Comment by sophiechapotat** [comment]
ça y est j'ai fini SF,terminer le reste de comédie et action aventure
jusquà 201 (vous aviez remarqué qu'il y a 800 action aventure???Je me suis
arrêter à 201. Le même nombre que les autres.
C'est fini normalement...Dites moi si tout est OK
Bonne soirée à demain
Sophie

2015-01-13 11:40 GMT-08:00 tonydimi notifications@github.com:

> J'ai également fini la partie "Comédie" et fais les 135 premiers de
> "Action-Aventure".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/m2dimi/ciwo/issues/1#issuecomment-69805732.

## 

sophie CHAPOTAT-LEMAISTRE
schapotat@gmail.com
06 88 20 41 01

**Comment by tonydimi** [comment]
Le compte est bon, on a les 1000 liens imdb pour les films.
Je ferme l'issue.

Merci !
