### ISSUE TITLE
Obtenir les données qui manquent depuis imdb avec le crawler de kimonolabs

### ISSUE THREAD

**Issue by dguiscpo** [m2dimi/ciwo#2]
Connectez vous sur un url imdb de la liste globale et utilisez kimonolab pour extraire les informations pour cette page spécifique, sauvegardez l'api.
Dans la page dédiée à cette nouvelle api sur kimonolabs, dans l'onglet `crawl setup` sélectionnez `manual url list` pour la `crawl_strategy`.
Collez votre liste des urls dans la textarea et crawlez ... !

**Comment by tonydimi** [comment]
C'est fait. A présent dans notre base, les données supplémentaires que nous avons sont :
- la note du film
- le nom du réalisateur
- le nom de l'acteur principal
- le synopsis du film

Comme vu ensemble en cours, je vous envoie le fichier CSV issu de Kimono.

**Comment by tonydimi** [comment]
Apparemment, le CSV contient uniquement le rating et le synopsis. J'avais pourtant bien pointé les acteur et les réalisateurs aussi... Comme vu ensemble par mail, je vous envoie l'export csv de la liste complète des films.

Merci

**Comment by tonydimi** [comment]
C'est fait, nous avons à présent toutes les données.
Je ferme l'issue.
Merci
