### ISSUE TITLE
[Données] Intégrer la colonne "Affiche grand format" dans la nouvelle base

### ISSUE THREAD

**Issue by tonydimi** [m2dimi/ciwo#6]
Peux-tu transférer les liens dans la nouvelle base envoyée hier stp.
Si tu as le temps, tu peux continuer également sur la nouvelle base.

Merci

**Comment by tonydimi** [comment]
C'est ok merci

**Comment by sophiechapotat** [comment]
Affiche grand format de 550 jusqu’ à 399 reste de 60 à 399

Sophie Chapotat
06 88 20 41 01
schapotat@gmail.com

**Comment by tonydimi** [comment]
Merci.
J'ai continué jusqu'à 300 et complété les trous (lorsqu'il n'y a pas de grande affiche sur Allocine). Mais il y a des films où l'affiche reste introuvable.

Reste à faire de 60 à 298. Faudrait que nous (Sophie, Marine, moi) continuons et finissons si possible demain.

Bonne soirée

**Comment by tonydimi** [comment]
Colonne AFFICHE intégrée dans la nouvelle base
